sudo: false
language: python
python:
  - 2.7
services:
  - redis
env:
  - FLASK=0.11.1
  - FLASK=0.9
install:
  - pip install -q Flask==$FLASK
  - pip install -q -r requirements.txt
  - pip install -q -e .
script:
  - python setup.py tests.py
